# _config.yml

# Select the theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # Required plugin for using remote themes

# Site settings
title: Barnabas Gavin Cangan
description: >- # this means to ignore newlines until "baseurl:"
  humanist. roboticist. PhD candidate at ETH Zurich.
# baseurl: "" # the subpath of your site, e.g. /blog (leave empty if hosting at root)
# url: "" # the base hostname & protocol for your site, e.g. http://example.com (usually set automatically by GitHub Pages)

# Optional: Add your Google Analytics ID
# google_analytics: UA-XXXXX-Y
